baseURL: https://chief.co.jp
languageCode: jp
title: Keisuke Iizuka 
paginate: 8
theme: hugo-theme-minos
markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1
params:
  description: 飯塚啓介です。主にコンピューターサイエンスとビジネスに興味があります。
  eng_description: Hi, my name is Keisuke Iizuka! I'm interested in Computer Science and Business!
  googleAnalytics: UA-129407596-3
  title: 飯塚啓介です。| Chief Blog
  smartToc: true
  author: Keisuke Iizuka
  keywords:
    - スタートアップ 
    - テクノロジー
    - コンピューターサイエンス
    - ビジネス
    - ブログ
menu: 
  main:
  - name: Home
    weight: 1
    url: /
  - name: All Contents
    weight: 10
    url: /posts/
author:
  github: 26keisuke
  twitter: keisuke_iizuka_
  email: 26keisuke@gmail.com